
export default {
    THEME_CHANGE:"THEME_CHANGE",//改变主题
    THEME_INIT:"THEME_INIT",//初始化这题
    SHOW_THEME_VIEW:"SHOW_THEME_VIEW",//显示选择主题对话框

    POPULAR_REFRESH:"POPULAR_REFRESH",//最热下拉刷新
    LOAD_POPULAR_FAIL:"LOAD_POPULAR_FAIL",//列表数据加载失败
    LOAD_POPULAR_SUCCESS:"LOAD_POPULAR_SUCCESS",//列表数据加载成功

    POPULAR_LOAD_MORE_SUCCESS:"POPULAR_LOAD_MORE_SUCCESS",//上拉加载更多成功
    POPULAR_LOAD_MORE_FAIL:"POPULAR_LOAD_MORE_FAIL",//上拉加载更多失败
    POPULAR_FLUSH_FAVORITE:"POPULAR_FLUSH_FAVORITE",

    TRENDING_REFRESH:"TRENDING_REFRESH",//趋势模块下拉刷新
    TRENDING_REFRESH_FAIL:"TRENDING_REFRESH_FAIL",//列表数据加载失败
    TRENDING_REFRESH_SUCCESS:"TRENDING_REFRESH_SUCCESS",//列表数据加载成功
    TRENDING_FLUSH_FAVORITE:"TRENDING_FLUSH_FAVORITE",

    TRENDING_LOAD_MORE_SUCCESS:"TRENDING_LOAD_MORE_SUCCESS",//上拉加载更多成功
    TRENDING_LOAD_MORE_FAIL:"TRENDING_LOAD_MORE_FAIL",//上拉加载更多失败

    FAVORITE_LOAD_DATA:"FAVORITE_LOAD_DATA",//加载收藏列表
    FAVORITE_LOAD_SUCCESS:"FAVORITE_LOAD_SUCCESS",//加载成功
    FAVORITE_LOAD_FAIL:"FAVORITE_LOAD_FAIL",//加载失败

    LANGUAGE_LOAD_SUCCESS:"LANGUAGE_LOAD_SUCCESS",
};